### ISSUE TITLE
RAP enforcement logic can be bypassed by attacker

### ISSUE THREAD

**Issue by Lavakumar** [DomdogSec/NodeSecurityShield#10]
This is similar to #9.

The RAP enforcement logic in https://github.com/DomdogSec/NodeSecurityShield/blob/main/lib/attackMonitoring.js uses several 

Node library methods. By overwriting any of then an attacker can potentially change the logic of how the RAP is verified and can bypass any restrictions placed by RAP.

**Comment by p1xxxel** [comment]
I have added a commit at #13  which is making a copy of `JSON.stringify` and `setTimeout` functions but there are following concerns :
- The `setTimeout` function is calling `Timeout` which then calls `incRefCount` and `initAsyncResource` and so on.., so even if we are making a copy of the function, an attacker can hook into any of the other functions and try to bypass the RAP enforcement logic.
- There are other methods that are being used like `regex.test` that can be hooked into as well, but these are very common methods and attempts to modify them by an attacker will most likely cause noticeable performance impact which can be detected.

As solving the above problems are quite complicated and are not required at this stage, maybe it can be added as an enhancement instead of a bug.

**Comment by Lavakumar** [comment]
Makes sense @p1xxxel. I think this should be sufficient at the moment. 
We can capture some of these advanced scenarios in the documentation under 'Known Limitations'.
